### ISSUE TITLE
[BUG] Custom Model Upload Failure in OpenSearch 2.11 with Sparse Model

### ISSUE THREAD

**Issue by kuro96al** [opensearch-project/ml-commons#1710]
What is the bug?
In OpenSearch 2.11, when attempting to regist a custom sparse model (specifically, a SPLADE model), the process fails with an error message: "Find multiple model files, but expected only one". The zip file contains only two files: splade-eng.onnx and tokenizer.json.

How can one reproduce the bug?

Utilize OpenSearch 2.11. 
Regist a custom sparse model (SPLADE model).
The model regist process fails.
Error message displayed: "Find multiple model files, but expected only one".
What is the expected behavior?
The expected behavior is the successful registration of the custom sparse model without encountering an error.

What is your host/environment?

OS: [Specific OS not provided]
Version: OpenSearch 2.11
Plugins: [Specific plugins not provided, if any]
Do you have any screenshots?

Do you have any additional context?
The model being registered is a SPLADE model. The contents of the zip file being registered include only splade-eng.onnx and tokenizer.json, with no additional files present.

**Comment by kuro96al** [comment]
<img width="761" alt="スクリーンショット 2023-11-29 20 39 46" src="https://github.com/opensearch-project/ml-commons/assets/22856873/0a267c98-c875-46f6-993f-36dee865e4d8">

**Comment by dhrubo-os** [comment]
@xinyual could you please look into this issue? Thanks.

**Comment by xinyual** [comment]
Also, if you are using splade model, we recommend you to use our own pretrained model https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/. It has better performance.

**Comment by kuro96al** [comment]
Thank you for the recommendation. Regarding English, I also agree that using the custom pretrained model you suggested would be beneficial. However, my primary interest lies in using and potentially training a Japanese language model with OpenSearch. Are there any published methods for creating ONNX or PyTorch models? I'm also interested in knowing if there are any resources available for learning how to train these models.

**Comment by xinyual** [comment]
You can use pytorch to have a try for generating TorchScript model. https://pytorch.org/docs/stable/jit.html

**Comment by kuro96al** [comment]
I tried converting it to PyTorch once, but it was unsuccessful. I would appreciate it if you could provide me with some examples of model conversions that are available in OpenSearch.

**Comment by zhichao-aws** [comment]
@kuro96al Here is a demo script to trace a .pt model which can be used in OpenSearch:
```
import torch
from transformers import AutoTokenizer, AutoModelForMaskedLM

class NeuralSparseModel(torch.nn.Module):
    def __init__(self,bert):
        super().__init__()
        self.bert = bert
        
    def forward(self, input: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        result = self.bert(input_ids=input["input_ids"],attention_mask=input["attention_mask"])[0]
        values, _ = torch.max(result*input["attention_mask"].unsqueeze(-1), dim=1)
        values = torch.log(1 + torch.relu(values))
        return {"output":values}

bert = AutoModelForMaskedLM.from_pretrained("/path-to-your-bert-mlm-model/")
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = NeuralSparseModel(bert)

text = ['sample text '*10]*4
input = tokenizer(text,
                            add_special_tokens=True,
                            padding="longest",  # pad to max sequence length in batch
                            truncation="longest_first",  # truncates to self.max_length
                            max_length=512,
                            return_attention_mask=True,
                            return_token_type_ids=False,
                            return_tensors="pt"
                 )
traced_model = torch.jit.trace(NeuralSparseModel(bert_bi), dict(input),strict=False)
torch.jit.save(traced_model, "target/save/path")
```

You can replace the model/tokenizer path and target save path based on your requirements

**Comment by kuro96al** [comment]
Thank you very much. I will refer to what I have received and try it out with a Japanese model.

**Comment by gitcarbs** [comment]
@kuro96al how did you create the zip file, was it using the macOS Compress feature?

I encountered a similar issue, and it turned out my zip file contained that additional `__MACOSX` directory. Its presence throws off the Opensearch model loading function.

I suggest you rebuild the zip, using this command to ensure you only get the relevant files in the zip

```
zip -r -X model.zip * 
```

**Comment by marevol** [comment]
I tried a custom sparse encoding model on OpenSearch 2.11.1, and it works.
```
import torch
from transformers import AutoTokenizer, AutoModelForMaskedLM
from typing import Dict

model_path = "naver_ecir23-scratch-tydi-japanese-splade-torch_script"
# !mkdir -p {model_path}

class NeuralSparseModel(torch.nn.Module):
    def __init__(self,bert):
        super().__init__()
        self.bert = bert
        
    def forward(self, input: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        result = self.bert(input_ids=input["input_ids"],attention_mask=input["attention_mask"])[0]
        values, _ = torch.max(result*input["attention_mask"].unsqueeze(-1), dim=1)
        values = torch.log(1 + torch.relu(values))
        return {"output":values}

tokenizer = AutoTokenizer.from_pretrained("naver/ecir23-scratch-tydi-japanese-splade")
bert = AutoModelForMaskedLM.from_pretrained("naver/ecir23-scratch-tydi-japanese-splade")
model = NeuralSparseModel(bert)

text = ['sample text '*10]*4
input = tokenizer(text,
                            add_special_tokens=True,
                            padding=True,
                            truncation=True,
                            max_length=512,
                            return_attention_mask=True,
                            return_token_type_ids=False,
                            return_tensors="pt"
                 )
traced_model = torch.jit.trace(model, dict(input),strict=False)
torch.jit.save(traced_model, f"{model_path}/ecir23-scratch-tydi-japanese-splade.pt")
tokenizer.save_pretrained(model_path)
# !cd {model_path}
# !zip ../{model_path}.zip *
# !shasum -a 256 ../{model_path}.zip
```
Then, copy the zip file to a directory that OpenSearch can read.
To register it as a custom model, the request is as follows:
```
$ curl -XPOST "http://localhost:9200/_plugins/_ml/models/_register" -H 'Content-Type: application/json' -d'
{
  "name": "naver/ecir23-scratch-tydi-japanese-splade_torch_script",
  "version": "1.0.0",
  "model_group_id": "<your group model id>",
  "description": "This is a sparse encoder model.",
  "function_name": "SPARSE_ENCODING",
  "model_format": "TORCH_SCRIPT",
  "model_content_hash_value": "<hash value from shasum>",
        "url": "file:///usr/share/opensearch/data/naver_ecir23-scratch-tydi-japanese-splade-torch_script.zip",
   "model_config": {
      "model_type": "bert",
     "embedding_dimension": 768,
    "framework_type": "sentence_transformers"
  }
}'
```
So, TorchScript model looks good to me.

**Comment by kuro96al** [comment]
This is a different issue, but do you know a solution for this?
{
  "model_id": "oHSpVY4B3eZG-EXv_cbd",
  "task_type": "DEPLOY_MODEL",
  "function_name": "SPARSE_ENCODING",
  "state": "FAILED",
  "worker_node": [
    "ybdsNWCpRT6pexqyy-eR1A",
    "SRiqjhfdRV2udioS_rO5mA",
    "TsBfIkraTvWi0yFJI_UMUw"
  ],
  "create_time": 1710835574640,
  "last_update_time": 1710835581907,
  "error": """{"ybdsNWCpRT6pexqyy-eR1A":"Exception java.lang.IllegalArgumentException: Invalid characters in hostname [in thread \"opensearch[opensearch-cluster-master-0][opensearch_ml_deploy][T#3]\"]","SRiqjhfdRV2udioS_rO5mA":"Exception java.lang.IllegalArgumentException: Invalid characters in hostname [in thread \"opensearch[opensearch-cluster-master-2][opensearch_ml_deploy][T#4]\"]","TsBfIkraTvWi0yFJI_UMUw":"Exception java.lang.IllegalArgumentException: Invalid characters in hostname [in thread \"opensearch[opensearch-cluster-master-1][opensearch_ml_deploy][T#3]\"]"}""",
  "is_async": true
}

**Comment by zane-neo** [comment]
Is there any error stack trace you can find on your cluster?

**Comment by xinyual** [comment]
@kuro96al Can you provide your register and deploy request body here?

**Comment by kuro96al** [comment]
I attempted the process again with version 2.12.0. Here is the log for your review.
It seems likely that the cause is that the worker node's ID (hostname) contains an underscore.
```
{
  "model_id": "4IkQX44Boe7kBZjFFaWy",
  "task_type": "DEPLOY_MODEL",
  "function_name": "SPARSE_ENCODING",
  "state": "FAILED",
  "worker_node": [
    "lf5waQHlTZSusfZtL_4HGA",
    "ymOmvHY7TzKzt9m21G-2sg",
    "N1vza14WSb2G1Y59GEpy6Q"
  ],
  "create_time": 1710991907939,
  "last_update_time": 1710991915629,
  "error": """{"lf5waQHlTZSusfZtL_4HGA":"Invalid character \\u005f in hostname","ymOmvHY7TzKzt9m21G-2sg":"Invalid character \\u005f in hostname","N1vza14WSb2G1Y59GEpy6Q":"Invalid character \\u005f in hostname"}""",
  "is_async": true
}
```

```
[2024-03-21T03:31:55,180][ERROR][o.o.m.m.MLModelManager   ] [opensearch-cluster-master-0] Failed to retrieve model 4IkQX44Boe7kBZjFFaWy
org.opensearch.ml.common.exception.MLException: Failed to deploy model 4IkQX44Boe7kBZjFFaWy
        at org.opensearch.ml.engine.algorithms.DLModel.lambda$loadModel$1(DLModel.java:294) ~[?:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
        at org.opensearch.ml.engine.algorithms.DLModel.loadModel(DLModel.java:247) ~[?:?]
        at org.opensearch.ml.engine.algorithms.DLModel.initModel(DLModel.java:139) ~[?:?]
        at org.opensearch.ml.engine.MLEngine.deploy(MLEngine.java:125) ~[?:?]
        at org.opensearch.ml.model.MLModelManager.lambda$deployModel$51(MLModelManager.java:1020) ~[?:?]
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.12.0.jar:2.12.0]
        at org.opensearch.ml.model.MLModelManager.lambda$retrieveModelChunks$72(MLModelManager.java:1553) [opensearch-ml-2.12.0.0.jar:2.12.0.0]
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.12.0.jar:2.12.0]
        at org.opensearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:78) [opensearch-2.12.0.jar:2.12.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913) [opensearch-2.12.0.jar:2.12.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.12.0.jar:2.12.0]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at org.opensearch.ml.engine.algorithms.DLModel.doLoadModel(DLModel.java:185) ~[?:?]
        at org.opensearch.ml.engine.algorithms.DLModel.lambda$loadModel$1(DLModel.java:280) ~[?:?]
        ... 14 more
Caused by: java.lang.IllegalArgumentException: Invalid character \u005f in hostname
        at java.base/java.net.HostPortrange.toLowerCase(HostPortrange.java:190) ~[?:?]
        at java.base/java.net.HostPortrange.<init>(HostPortrange.java:150) ~[?:?]
        at java.base/java.net.URLPermission$Authority.<init>(URLPermission.java:533) ~[?:?]
        at java.base/java.net.URLPermission.parseURI(URLPermission.java:501) ~[?:?]
        at java.base/java.net.URLPermission.init(URLPermission.java:210) ~[?:?]
        at java.base/java.net.URLPermission.<init>(URLPermission.java:190) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.URLtoSocketPermission(HttpURLConnection.java:1158) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1107) ~[?:?]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:141) ~[?:?]
        at ai.djl.util.Ec2Utils.openConnection(Ec2Utils.java:163) ~[?:?]
        at ai.djl.util.Ec2Utils.callHome(Ec2Utils.java:107) ~[?:?]
        at ai.djl.engine.Engine.initEngine(Engine.java:93) ~[?:?]
        at ai.djl.engine.Engine.<clinit>(Engine.java:61) ~[?:?]
        at org.opensearch.ml.engine.algorithms.DLModel.doLoadModel(DLModel.java:185) ~[?:?]
        at org.opensearch.ml.engine.algorithms.DLModel.lambda$loadModel$1(DLModel.java:280) ~[?:?]
        ... 14 more
```

**Comment by xinyual** [comment]
Can you provide your request body? It seems your URL has something wrong.

**Comment by kuro96al** [comment]
POST /_plugins/_ml/models/Rs17ZY4Bkp8k158ojM0N/_deploy

POST _plugins/_ml/models/_register
{
  "name": "naver/ecir23-scratch-tydi-japanese-splade_torch_script",
  "version": "1.0.0",
  "model_group_id": "3397ZY4BCNjHMSbAdraI",
  "description": "This is a sparse encoder model.",
  "function_name": "SPARSE_ENCODING",
  "model_format": "TORCH_SCRIPT",
  "model_content_hash_value": "<model hash>",
        "url": "<model url>",
   "model_config": {
      "model_type": "bert",
     "embedding_dimension": 768,
    "framework_type": "sentence_transformers"
  }
}

**Comment by xinyual** [comment]
Sorry for late reply. It seems you are right. The problem is from the DJL and it is because the wrong host.

**Comment by dhrubo-os** [comment]
Closing the issue, Please feel free to open the issue again if needed.

**Comment by kuro96al** [comment]
@xinyual Does this mean there is an issue with the implementation of OpenSearch? (Can it be circumvented with settings or is my configuration not modern enough?)"

**Comment by xinyual** [comment]
@kuro96al Hi, do you try opensearch on an EC2? If so, could you please provide your instance-id or check whether there is an underscore inside the instance-id? I check the code, it seems the url is not related with work node name and it is the implementation of DJL which opensearch depends on. It is related to your instance-id/region.

**Comment by kuro96al** [comment]
@xinyual We are using an on-premises environment. We are installing using Helm on a Kubernetes (k8s) cluster.

https://github.com/opensearch-project/helm-charts

**Comment by xinyual** [comment]
@kuro96al Can you provide some doc so I can follow to reproduce such problem? Also, could you please provide the config file to define some environment variables?

**Comment by kuro96al** [comment]
```
---
image:
  repository: "{{ opensearch_image }}"
  tag: "{{ opensearch_version }}"
resources: {{ container_opensearch_resources }}
opensearchLifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "until curl -m 10 -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'; do sleep 5; done"]
keystore:
  - secretName: keystore-secrets
config:
  opensearch.yml: |
    cluster.name: opensearch-cluster

    # Bind to all interfaces because we don't know what IP address Docker will assign to us.
    network.host: 0.0.0.0

    plugins:
      security:
        disabled: true
    cluster.indices.replication.strategy: 'SEGMENT'
    s3.client.default.endpoint: test:80
    s3.client.default.protocol: http
    s3.client.default.region: "dev"
    s3.client.default.path_style_access: "true"
    node.attr.remote_store.segment.repository: my-repo
    node.attr.remote_store.translog.repository: my-repo
    node.attr.remote_store.state.repository: my-repo
    node.attr.remote_store.repository.my-repo.type: s3
    node.attr.remote_store.repository.my-repo.settings.bucket: test
    node.attr.remote_store.repository.my-repo.settings.base_path: store-2
    node.attr.remote_store.repository.my-repo.settings.region: "dev"
service:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/_prometheus/metrics'
    prometheus.io/port: '9200'
opensearchJavaOpts: "{{ opensearch_java_opts }}"
persistence:
  enabled: false
extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
extraVolumes:
  - name: "opensearch-cluster-master"
    emptyDir: {}
extraVolumeMounts:
  - name: "opensearch-cluster-master"
    mountPath: /usr/share/opensearch/data
```

**Comment by kuro96al** [comment]
That would be the values.yaml file for OpenSearch Helm chart.

**Comment by zhichao-aws** [comment]
> Has someone tried this for Splade V3? I have tried `naver/ecir23-scratch-tydi-japanese-splade` and it works indeed, but I can't get it working for [Splade-V3](https://huggingface.co/naver/splade-v3). Getting this error: https://forum.opensearch.org/t/error-when-deploying-pretrained-model-unknown-builtin-op-aten-scaled-dot-product-attention/24040

Have you tried to downgrade the torch to 1.13 or 2.0?

The error message looks like new torch operator not supported by old djl version.

**Comment by jzhang2-coveo** [comment]
> > Has someone tried this for Splade V3? I have tried `naver/ecir23-scratch-tydi-japanese-splade` and it works indeed, but I can't get it working for [Splade-V3](https://huggingface.co/naver/splade-v3). Getting this error: https://forum.opensearch.org/t/error-when-deploying-pretrained-model-unknown-builtin-op-aten-scaled-dot-product-attention/24040
> 
> Have you tried to downgrade the torch to 1.13 or 2.0?
> 
> The error message looks like new torch operator not supported by old djl version.

Yes I did, but the Splade V3 needs dependencies that exists in PyTorch > 2.0

This is my script to prepare the ZIp file with model:
```
import torch
import shutil
from transformers import AutoTokenizer, AutoModelForMaskedLM
from typing import Dict

model = "splade-v3"
model_path = "models"
model_path_with_model = "{}/{}".format(model_path, model)
model_hf = "naver/splade-v3"
# !mkdir -p {model_path}

class NeuralSparseModel(torch.nn.Module):
    def __init__(self,bert):
        super().__init__()
        self.bert = bert
        
    def forward(self, input: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        result = self.bert(input_ids=input["input_ids"],attention_mask=input["attention_mask"])[0]
        values, _ = torch.max(result*input["attention_mask"].unsqueeze(-1), dim=1)
        values = torch.log(1 + torch.relu(values))
        return {"output":values}


tokenizer = AutoTokenizer.from_pretrained(model_hf)
bert = AutoModelForMaskedLM.from_pretrained(model_hf)
model = NeuralSparseModel(bert)

text = ['sample text '*10]*4
input = tokenizer(text,
                            add_special_tokens=True,
                            padding=True,
                            truncation=True,
                            max_length=512,
                            return_attention_mask=True,
                            return_token_type_ids=False,
                            return_tensors="pt"
                 )
traced_model = torch.jit.trace(model, dict(input),strict=False)
torch.jit.save(traced_model, f"{model_path_with_model}.pt")
tokenizer.save_pretrained(model_path_with_model)

# Create a zip file from the directory
shutil.make_archive(base_name=model_path_with_model, format="zip", root_dir=model_path_with_model)

print(f"Created zip file: {model_path_with_model}.zip")
```

With PyTorch 1.13 I get this error:
```
No module named 'torch.distributed.tensor'
```

After upgrading to 2.0 I get this error:
```
module 'torch' has no attribute 'compiler'
```

Upgrading to 2.5.1 has no errors, but then I get the [dependency error](https://forum.opensearch.org/t/error-when-deploying-pretrained-model-unknown-builtin-op-aten-scaled-dot-product-attention/24040) when deploying the model.

I see that in  OpenSearch `3.0.0-beta1` that `ml-commons` has been upgraded to `2.5.1`. Would that fix this issue? I see that today is the first day that the [release window](https://opensearch.org/releases.html) opens.

**Comment by zhichao-aws** [comment]
@jzhang2-coveo 

I can run the script at my local env with pytorch version 1.12.1. It's wierd if the error only occurs to `splade-v3`. Because different splade models are just BertForMaskedLM with different parameter weights. From torch side all operators are identical. I assume you'll get same error message tracing different SPLADE.

The exception `No module named 'torch.distributed.tensor'` and `module 'torch' has no attribute 'compiler'` are caused by `transformers` version, you can try downgrade it to match the torch 1.13.1 version.

**Comment by jzhang2-coveo** [comment]
@zhichao-aws I downgraded to 1.13.1

```
pip3 install torch==1.13.1 torchvision torchaudio accelerate transformers

Successfully installed accelerate-1.2.1 tokenizers-0.21.1 torch-1.13.1 torchaudio-0.13.1 torchvision-0.14.1 transformers-4.51.1
```

But then still saw issues with `No module named 'torch.distributed.tensor'` so upgraded transformers to 4.32 too.

Then it successfully creates the zip file, but then still getting `Unknown builtin op: aten::scaled_dot_product_attention` error. I am wondering whether you or someone else can run this. I am not sure whether I should create an issue or whether it's already solved in 3-beta.

```
2025-04-08 11:51:18 [2025-04-08T09:51:18,716][ERROR][o.o.m.e.a.DLModel        ] [opensearch-node1] Failed to deploy model l_7PFJYBSBFZy6StavCJ
2025-04-08 11:51:18 ai.djl.engine.EngineException: 
2025-04-08 11:51:18 Unknown builtin op: aten::scaled_dot_product_attention.
2025-04-08 11:51:18 Here are some suggestions: 
2025-04-08 11:51:18     aten::_scaled_dot_product_attention
2025-04-08 11:51:18 
2025-04-08 11:51:18 The original call is:
2025-04-08 11:51:18   File "code/__torch__/transformers/models/bert/modeling_bert.py", line 196
2025-04-08 11:51:18     x1 = torch.view(_40, [_42, int(_43), 12, 64])
2025-04-08 11:51:18     value_layer = torch.permute(x1, [0, 2, 1, 3])
2025-04-08 11:51:18     attn_output = torch.scaled_dot_product_attention(query_layer, key_layer, value_layer, attention_mask)
2025-04-08 11:51:18                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
2025-04-08 11:51:18     attn_output0 = torch.transpose(attn_output, 1, 2)
2025-04-08 11:51:18     input = torch.reshape(attn_output0, [_30, _31, 768])
2025-04-08 11:51:18 
2025-04-08 11:51:18     at ai.djl.pytorch.jni.PyTorchLibrary.moduleLoad(Native Method) ~[pytorch-engine-0.31.1.jar:?]
2025-04-08 11:51:18     at ai.djl.pytorch.jni.JniUtils.loadModule(JniUtils.java:1789) ~[pytorch-engine-0.31.1.jar:?]
2025-04-08 11:51:18     at ai.djl.pytorch.engine.PtModel.load(PtModel.java:99) ~[pytorch-engine-0.31.1.jar:?]
2025-04-08 11:51:18     at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:172) ~[api-0.31.1.jar:?]
2025-04-08 11:51:18     at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:151) ~[api-0.31.1.jar:?]
2025-04-08 11:51:18     at org.opensearch.ml.engine.algorithms.DLModel.doLoadModel(DLModel.java:217) ~[opensearch-ml-algorithms-3.0.0.0-alpha1.jar:?]
2025-04-08 11:51:18     at org.opensearch.ml.engine.algorithms.DLModel.lambda$loadModel$1(DLModel.java:286) [opensearch-ml-algorithms-3.0.0.0-alpha1.jar:?]
2025-04-08 11:51:18     at java.base/java.security.AccessController.doPrivileged(AccessController.java:571) [?:?]
2025-04-08 11:51:18     at org.opensearch.ml.engine.algorithms.DLModel.loadModel(DLModel.java:252) [opensearch-ml-algorithms-3.0.0.0-alpha1.jar:?]
2025-04-08 11:51:18     at org.opensearch.ml.engine.algorithms.DLModel.initModel(DLModel.java:142) [opensearch-ml-algorithms-3.0.0.0-alpha1.jar:?]
2025-04-08 11:51:18     at org.opensearch.ml.engine.MLEngine.deploy(MLEngine.java:144) [opensearch-ml-algorithms-3.0.0.0-alpha1.jar:?]
2025-04-08 11:51:18     at org.opensearch.ml.model.MLModelManager.lambda$deployModel$49(MLModelManager.java:1277) [opensearch-ml-3.0.0.0-alpha1.jar:3.0.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-3.0.0-alpha1.jar:3.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.ml.model.MLModelManager.lambda$retrieveModelChunks$77(MLModelManager.java:2153) [opensearch-ml-3.0.0.0-alpha1.jar:3.0.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-3.0.0-alpha1.jar:3.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:78) [opensearch-3.0.0-alpha1.jar:3.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:994) [opensearch-3.0.0-alpha1.jar:3.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-3.0.0-alpha1.jar:3.0.0-alpha1]
2025-04-08 11:51:18     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
2025-04-08 11:51:18     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
2025-04-08 11:51:18     at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2025-04-08 11:51:18 [2025-04-08T09:51:18,745][ERROR][o.o.m.m.MLModelManager   ] [opensearch-node1] Failed to retrieve model l_7PFJYBSBFZy6StavCJ
2025-04-08 11:51:18 org.opensearch.ml.common.exception.MLException: Failed to deploy model l_7PFJYBSBFZy6StavCJ
2025-04-08 11:51:18     at org.opensearch.ml.engine.algorithms.DLModel.lambda$loadModel$1(DLModel.java:300) ~[?:?]
2025-04-08 11:51:18     at java.base/java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
2025-04-08 11:51:18     at org.opensearch.ml.engine.algorithms.DLModel.loadModel(DLModel.java:252) ~[?:?]
2025-04-08 11:51:18     at org.opensearch.ml.engine.algorithms.DLModel.initModel(DLModel.java:142) ~[?:?]
2025-04-08 11:51:18     at org.opensearch.ml.engine.MLEngine.deploy(MLEngine.java:144) ~[?:?]
2025-04-08 11:51:18     at org.opensearch.ml.model.MLModelManager.lambda$deployModel$49(MLModelManager.java:1277) ~[?:?]
2025-04-08 11:51:18     at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-3.0.0-alpha1.jar:3.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.ml.model.MLModelManager.lambda$retrieveModelChunks$77(MLModelManager.java:2153) [opensearch-ml-3.0.0.0-alpha1.jar:3.0.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-3.0.0-alpha1.jar:3.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:78) [opensearch-3.0.0-alpha1.jar:3.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:994) [opensearch-3.0.0-alpha1.jar:3.0.0-alpha1]
2025-04-08 11:51:18     at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-3.0.0-alpha1.jar:3.0.0-alpha1]
2025-04-08 11:51:18     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
2025-04-08 11:51:18     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
2025-04-08 11:51:18     at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
2025-04-08 11:51:18 Caused by: ai.djl.engine.EngineException: 
2025-04-08 11:51:18 Unknown builtin op: aten::scaled_dot_product_attention.
2025-04-08 11:51:18 Here are some suggestions: 
2025-04-08 11:51:18     aten::_scaled_dot_product_attention
2025-04-08 11:51:18 
2025-04-08 11:51:18 The original call is:
2025-04-08 11:51:18   File "code/__torch__/transformers/models/bert/modeling_bert.py", line 196
2025-04-08 11:51:18     x1 = torch.view(_40, [_42, int(_43), 12, 64])
2025-04-08 11:51:18     value_layer = torch.permute(x1, [0, 2, 1, 3])
2025-04-08 11:51:18     attn_output = torch.scaled_dot_product_attention(query_layer, key_layer, value_layer, attention_mask)
2025-04-08 11:51:18                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
2025-04-08 11:51:18     attn_output0 = torch.transpose(attn_output, 1, 2)
2025-04-08 11:51:18     input = torch.reshape(attn_output0, [_30, _31, 768])
2025-04-08 11:51:18 
2025-04-08 11:51:18     at ai.djl.pytorch.jni.PyTorchLibrary.moduleLoad(Native Method) ~[?:?]
2025-04-08 11:51:18     at ai.djl.pytorch.jni.JniUtils.loadModule(JniUtils.java:1789) ~[?:?]
2025-04-08 11:51:18     at ai.djl.pytorch.engine.PtModel.load(PtModel.java:99) ~[?:?]
2025-04-08 11:51:18     at ai.djl.repository.zoo.BaseModelLoader.loadModel(BaseModelLoader.java:172) ~[?:?]
2025-04-08 11:51:18     at ai.djl.repository.zoo.Criteria.loadModel(Criteria.java:151) ~[?:?]
2025-04-08 11:51:18     at org.opensearch.ml.engine.algorithms.DLModel.doLoadModel(DLModel.java:217) ~[?:?]
2025-04-08 11:51:18     at org.opensearch.ml.engine.algorithms.DLModel.lambda$loadModel$1(DLModel.java:286) ~[?:?]
2025-04-08 11:51:18     ... 14 more
```

**Comment by zhichao-aws** [comment]
@jzhang2-coveo 

Here is one fault in the code
```
torch.jit.save(traced_model, f"{model_path_with_model}.pt")

should be

torch.jit.save(traced_model, f"{model_path_with_model}/splade-v3.pt")
```

After fix it, it works at my env (using opensearch 2.12.0). Although it throws some warnings about torch/transformers/numpy versions compatibiltity
```
conda create -n trace python=3.9
conda activate trace
pip install torch==1.13.1 transformers==4.32.0
# run the trace code, get splade-v3.zip
# upload to s3, get sha256, then use presign link to register
# successfully run deploy and predict
```

**Comment by jzhang2-coveo** [comment]
@zhichao-aws I can deploy the model now, but when doing predictions with the ingest pipeline it's returning this error:

```
"error": {
                "root_cause": [
                    {
                        "type": "null_pointer_exception",
                        "reason": "Cannot invoke \"java.util.List.iterator()\" because \"tensorsList\" is null"
                    }
                ],
                "type": "null_pointer_exception",
                "reason": "Cannot invoke \"java.util.List.iterator()\" because \"tensorsList\" is null"
            }
```

This is the ingest pipeline I tried as a test:
```
PUT http://localhost:9200/_ingest/pipeline/sparse-test-pipeline
{
  "processors": [
    {
      "text_embedding": {
        "model_id": "Zpz8G5YBz-EeAUGffzz1",
        "field_map": {
          "title": "title_embedding"
        }
      }
    },
    {
      "text_embedding": {
        "model_id": "Zpz8G5YBz-EeAUGffzz1",
        "field_map": {
          "txt": "txt_embedding"
        }
      }
    }
  ]
}
```

This is how I did the test:
```
POST http://localhost:9200/_ingest/pipeline/sparse-test-pipeline/_simulate
{
  "docs": [
    {
      "_index": "my-index",
      "_id": "1",
      "_source": {
        "title": "John Doe",
        "txt": "This is John Doe"
      }
    },
    {
      "_index": "my-index",
      "_id": "2",
      "_source": {
        "title": "Jane Doe",
        "txt": "This is Jane Doe"
      }
    }
  ]
}
```
